### ISSUE TITLE
window_manager_service_sway.c:on_ipc_recv_dispatch() failed to subscribe to events.

### ISSUE THREAD

**Issue by TheHelplessCelt** [ldelossa/way-shell#12]
I have this issue where I get a core dump when running way-shell on Fedora 40. it installed fine, it compiled fine. it does the same thing in toolbox and installed locally. Here's the exact error. I have swayfx installed and its the latest version. Am I doing something wrong?

`
** (way-shell:49103): ERROR **: 14:24:10.413: window_manager_service_sway.c:on_ipc_recv_dispatch() failed to subscribe to events.
Trace/breakpoint trap (core dumped)
`

**Comment by ldelossa** [comment]
Hey @TheHelplessCelt 

Latest HEAD requires the ability to listen for 'output' events. This was introduced in Sway 1.9. 

While way-shell is under activate development, it will follow follow latest releases like this. When a release is finally created, I'll pin to a particular version. 

Are you able to upgrade to Sway 1.9?

**Comment by ldelossa** [comment]
Reopen if this is still an issue.
