### ISSUE TITLE
Please replace binary data in source file

### ISSUE THREAD

**Issue by b1rger** [ldelossa/way-shell#16]
Something like this
https://github.com/ldelossa/way-shell/blob/d87085842dc0282064db8ab222b24887a316feb4/src/gresources.c#L9
makes it basically impossible to review the code or provide patches.

(also from a security perspective something like this looks sketchy)

**Comment by ldelossa** [comment]
Done: https://github.com/ldelossa/way-shell/commit/cff6fa72a139390029cfd9127a7fd10ebcfe1b6d

gresources is now a compile time artifact used for building Way-Shell.
