### ISSUE TITLE
Questions regarding licenses

### ISSUE THREAD

**Issue by b1rger** [ldelossa/way-shell#18]
Hi! There are a couple of files whose license situation is not clear to me:
* services/logind_service/logind_manager_dbus.*
* services/logind_service/logind_session_dbus.*
* services/media_player_service/media_player_dbus.*
* services/notifications_service/notifications_dbus.*
* services/power_profiles_service/power_profiles_dbus.*

The all have a similar header:
```
* This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from.
 ```

I guess they are derived from the dbus xml files in `data/dbus-interfaces`? But I haven't found any copyright statements in those files. The login manager and login session dbus interface come from systemd, so the xml file probably have the same copyright as upstream systemd, but I haven't found any sources for the other files.

Thanks!

**Comment by ldelossa** [comment]
Yes I think your comments about systemd is correct so lets see..

SystemD License: GPL-2.0 
* services/logind_service/logind_manager_dbus.*
* services/logind_service/logind_session_dbus.*

MPRIS License: GNU Lesser General Public License as published by the Free Software Foundation
[Source](https://specifications.freedesktop.org/mpris-spec/latest/) (First div with copyright/license info). 
* services/media_player_service/media_player_dbus.*

This one I'm having trouble finding. 
It **should** be same as MPRIS (GNU Lesser General Public License), but can't seem to find the spec repo at:
https://gitlab.freedesktop.org/explore/groups
services/notifications_service/notifications_dbus.*

PowerProfilesDaemon: GPLv3 
[Source](https://gitlab.freedesktop.org/upower/power-profiles-daemon)
services/power_profiles_service/power_profiles_dbus.*

**Comment by b1rger** [comment]
Ok, thanks, that helped a lot! According to copyright files of other Debian packages, the `org.freedesktop.Notifications.xml` is GPL-3, copyright by Canonical
