### ISSUE TITLE
Install location for glib schemas

### ISSUE THREAD

**Issue by joetoth** [ldelossa/way-shell#28]
I installed way-shell under a different directory other than /usr. It only worked after I did:
``` sudo install -D data/org.ldelossa.way-shell.gschema.xml /usr/share/glib-2.0/schemas/```

I'm not sure if this is a glib requirement?

Cool project! Me, personally, I only want the "systray" capabilities. My current bar image below. Clicking on volume brings up pulse, wifi brings up a dropdown and bluetooth brings up bluey and the calendar just opens a floating `google-chrome --app=https://calendar.google.com`

It gets the job done, but it's not cohesive and as nice as yours.

![Sun Jun 23 14:23:07 EDT 2024](https://github.com/ldelossa/way-shell/assets/13778/17d643f0-e45b-4ca2-a1bb-08c61c9164e7)

**Comment by ldelossa** [comment]
Hey there. 

The schema location is configurable. https://github.com/ldelossa/way-shell/blob/main/Makefile#L3 

You'll want to set that to wherever your distro of choice stores their schemas and then run `make install-gschema` to compile it.
