### ISSUE TITLE
Don't use absolute paths in `Makefile`

### ISSUE THREAD

**Issue by b1rger** [ldelossa/way-shell#3]
Hi,

nice project! I tried to create a Debian package from it and succeeded! I'm just throwing out there what caught my eye: in the `Makefile` it would be nice if you could use `PREFIX` instead of hardcoding `/usr/local/bin`, that would make the life easier for prospective package maintainers. Also `sudo` isn't usuall run inside the `Makefile`, but rather just as: `sudo make install` as the last step. You could also use `install` instead of `cp`

**Comment by ldelossa** [comment]
Ah I see. 

Yes, Ive never packaged into deb or rpm. 

Do you have any other requirements for Makefile that will make packaging easier? If you want you can also open PR with any edits that makes deb packaging easier.

**Comment by b1rger** [comment]
> Do you have any other requirements for Makefile that will make packaging easier?

Not at the moment, but I'll keep an eye on the project and if you do an official release at some point, I'll probably try to create an official Debian package. (we will then have to think about what to do with `cmd_tree` - if it should be a separate project, I'd have to package that first)

**Comment by ldelossa** [comment]
Hello @b1rger 

I have updated the Makefile heavily to support building in copr. 

If you are still keen to, it should be easier to create a Debian package now. 

No sudo is used, absolute paths are removed (other then systemd user unit path), and no more git-submodules, code is vendored in directly.

**Comment by ldelossa** [comment]
Gonna close this now, reopen if you see this as still an issue.
