### ISSUE TITLE
IPC socket does not exist at /run/user/1000/way-shell.sock

### ISSUE THREAD

**Issue by rgbmew** [ldelossa/way-shell#47]
Howdy! I'm testing out way-shell on Fedora Sericea (the immutable/atomic version of Fedora with Sway as the default WM) via COPR, but running way-sh just informs me that there's no IPC socket.

I've read through the readme and COPR repo, but I don't see anything relating to creating a socket for way-shell. I've also read through all previous Issues and don't see a solution for the problem I'm having. Am I missing something with my Sway config?

Thanks!

**Comment by ldelossa** [comment]
Hey there. 

So I havent tried way-shell on an immutable OS just yet. Are you trying to run Way-Shell in a toolbox container or did you rpm-ostree install it?

**Comment by rgbmew** [comment]
Personally, I'm rpm-ostree'ing it, but I get the same socket error in Toolbox.

**Comment by ldelossa** [comment]
And where you run way-shell, do you have access to the socket its saying it can't find?

**Comment by rgbmew** [comment]
I'm no C programmer, so bear with me, but it seems like the socket isn't being created in the first place?

![2024-07-22T18:49:47,036270438-04:00](https://github.com/user-attachments/assets/4b8b7718-2c4a-4118-9e08-6398a816d99e)
![2024-07-22T18:57:40,773636885-04:00](https://github.com/user-attachments/assets/8048bea6-79c4-4caf-bcd3-6bbf7ca9ca0a)

Like, if there was a socket at /run/user/1000/way-shell.sock, wouldn't there be a file to represent that socket? And as far as I'm aware, /run in Silverblue is perfectly mutable, and it works just like in other distros; no weird Silverblue image-based stuff, so it *should* be able to make itself?

**Comment by ldelossa** [comment]
No worries! 

I would agree, I imagine that toolbox would mount in the run directly. Kinda weird way-shell is not creating the socket. Cant say ive seem this before. 

When you run way-shell on the cli, can you send me the logs, maybe we will get a clue.

**Comment by rgbmew** [comment]
Just running the program gives me

```
[catherine@silverblue ~]$ way-sh
[Error] IPC socket does not exist at /run/user/1000/way-shell.sock
```

Running it with strace gives me

```
[catherine@silverblue ~]$ strace -f way-sh
execve("/usr/bin/way-sh", ["way-sh"], 0x7ffcc5316bc8 /* 40 vars */) = 0
brk(NULL)                               = 0x563d512e8000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=54139, ...}) = 0
mmap(NULL, 54139, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f9e35531000
close(3)                                = 0
openat(AT_FDCWD, "/lib64/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\242\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
fstat(3, {st_mode=S_IFREG|0755, st_size=2440240, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9e3552f000
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 2034544, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f9e3533e000
mmap(0x7f9e35366000, 1495040, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x28000) = 0x7f9e35366000
mmap(0x7f9e354d3000, 319488, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x195000) = 0x7f9e354d3000
mmap(0x7f9e35521000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1e2000) = 0x7f9e35521000
mmap(0x7f9e35527000, 31600, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f9e35527000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9e3533b000
arch_prctl(ARCH_SET_FS, 0x7f9e3533b740) = 0
set_tid_address(0x7f9e3533ba10)         = 1982
set_robust_list(0x7f9e3533ba20, 24)     = 0
rseq(0x7f9e3533c060, 0x20, 0, 0x53053053) = 0
mprotect(0x7f9e35521000, 16384, PROT_READ) = 0
mprotect(0x563d2355d000, 4096, PROT_READ) = 0
mprotect(0x7f9e35578000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
munmap(0x7f9e35531000, 54139)           = 0
newfstatat(AT_FDCWD, "/run/user/1000/way-shell.sock", 0x7ffdeac44710, 0) = -1 ENOENT (No such file or directory)
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0), ...}) = 0
getrandom("\x9c\xc2\x5b\xa4\x4f\xf9\x7f\x79", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x563d512e8000
brk(0x563d51309000)                     = 0x563d51309000
write(1, "[Error] IPC socket does not exis"..., 67[Error] IPC socket does not exist at /run/user/1000/way-shell.sock
) = 67
exit_group(-1)                          = ?
+++ exited with 255 +++
```

It's the exact same output in Toolbox, as well.

If you'd like me to run it with a subcommand (I'm not sure if you have debugging built-in to the program), or another debugging tool, let me know :)

**Comment by ldelossa** [comment]
Please send logs for way-shell not way-sh

**Comment by rgbmew** [comment]
Oh my god, well that's embarrassing. I thought `way-sh` WAS the way-shell executable. Now that I'm running `way-shell`, it works perfectly. Sorry for wasting so much of your time!

If I could propose a change, maybe edit the readme to be more verbose about `way-shell` being the executable, and `way-sh` being the child script (executable? keybind "daemon"? Socket Speaker?)?
The line in the readme that particularly made me think this was, `Sway integrates with Way-Shell via its CLI way-sh.` To me, that reads as "`way-sh` is what you want to run, that's The command. Way-Shell is just the surname of way-sh."

Sorry again! Or moreso, thanks for helping me. I promise I'm not usually this dumb in person. LOL.

**Comment by ldelossa** [comment]
Haha no worries. Enjoy Way-Shell!
