### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by privat** [ldelossa/way-shell#49]
I compiled from source under Debian, everything works so far excepts for some icons that are missing

![foo](https://github.com/user-attachments/assets/038c0470-2853-4ed7-9f5b-dab1819df326)

Any idea what I should check?

**Comment by ldelossa** [comment]
Hey there. 

Way-Shell bases icons off the main Adwaita icon theme and uses icon names from this. 

So far, icon themes from distro/de maintainers have the best compatibility in my testing. 

Id recommend changing your icon theme to Adwaita: https://gitlab.gnome.org/GNOME/adwaita-icon-theme

The Cosmic Icon theme works very well too: https://github.com/pop-os/cosmic-icons

You can also just explore other themes, but not all themes implement all icons from Adwaita.

**Comment by privat** [comment]
thanks. what was missing is an icon theme. Adding the following in the sway config did the trick.

```
exec gsettings set org.gnome.desktop.interface icon-theme Adwaita
```

Maybe document it in the README in *Configuring Sway*

**Comment by ldelossa** [comment]
@privat thanks, I think a wikipage for this is in order :) You're not the first to have this question. thanks for the input.

**Comment by ldelossa** [comment]
https://github.com/ldelossa/way-shell/wiki/Icon-Themes-(And-Missing-Icons)
