### ISSUE TITLE
[Feature Request] Tray Icons

### ISSUE THREAD

**Issue by sand-r** [ldelossa/way-shell#57]
It would be awesome if you could add support for tray icons similar to what waybar has

**Comment by ldelossa** [comment]
On the list for sure. A bit lower priority then other things right now. Community contributions for this are more then welcome!

**Comment by ldelossa** [comment]
@sannagy90 I want to start looking in to this, do you happen to know of an app which always creates a tray icon, that I can open and close while I test the feature?

**Comment by sannagy90** [comment]
you should be able to test with `nm-applet --indicator` or `blueman-applet` which should both create tray icons!
Steam and Discord also should use tray icons, but those are proprietary - not sure if that matters.
Thank you for looking into this!

**Comment by ldelossa** [comment]
I am finding that not everyone implements the spec correctly (as it would appear at first blush): https://github.com/blueman-project/blueman/issues/2497

Not sure how wide spread this is.

**Comment by ldelossa** [comment]
https://github.com/ldelossa/way-shell/pull/61 - WIP PR for this. 

Kinda ugly, but a lot of software does not utilize the `VOID org.freedesktop.StatusNotifierWatcher.RegisterStatusNotifierItem (STRING service);` method correctly. 

Software is supposed to send the bus name, and then a `/StatusNotifierItem` object should be at root. 

Unfortunately, seems like a lot of software sends the object path where the `org.kde.StatusNotifierItem` interface is implemented. 

The unfortunate part of this, is that it does not allow us to find the bus name easily, without going thru the introspection API which involves parsing XML and will be rather slow. 

I think, we will try to just special case things, such that when we see an object path like `/org/ayatana/NotificationItem/nm_applet` we can map this in code to the bus we find it on `org.freedesktop.network-manager-applet`. This takes hard-coding tho :\

**Comment by ldelossa** [comment]
![image](https://github.com/user-attachments/assets/75bd9e19-c9b4-4bd1-9a6c-d2271140e8f3)

getting closer! Bugs to workout and have to handle updates but its going.

**Comment by ldelossa** [comment]
Couple notes on Gtk4 PopoverMenu. 

The way Gtk4 displays GMenu models (the data portion of a hierarchical menu) does bit include many features that the Menu dbus API provides. 

For instance: 
1. No icons
2. No sensibility (disable clicking) 
3. No radio/stateful buttons

It possible to implement these things with a Custom GMenuItem widget, but I wont do this on the first iteration of this feature. 

So, well conform to gtk4's wishes  w/r/t how menus should be displayed for now.

**Comment by ldelossa** [comment]
Hello @sand-r - are you able to provide feedback? https://github.com/ldelossa/way-shell/pull/61

**Comment by sand-r** [comment]
Took a quick look and it looks pretty good so far. I do see some missing icons with steam and bitwarden but no issues with blueman and discord. All apps besides blueman are flatpaks. I do have a local override for steam .desktop but not for bitwarden, so I'm not sure if that's related or not. I will do more testing in the upcoming days, thank you again for taking the time to add this feature.

![image](https://github.com/user-attachments/assets/43918895-2de8-4b02-adee-b310012bd9cf)

**Comment by ldelossa** [comment]
Hey there. 


So, I grabbed bitwarden from flathub.org. However, I dont see it advertising any anything any tray icon for us to display 🤔

Any specific about the app to get it to ask for a tray icon? I just loaded it, no further setup other then creating an account.

**Comment by sand-r** [comment]
You can enable the tray icon in the settings but it does look like you need an account to access settings... which is certainly a choice lol. For what it's worth I do see the same missing icon with OBS recorder, also installed from Flathub

**Comment by ldelossa** [comment]
Thanks! I see the missing Bitwarden icon now. Will check it out. And ACK on OBS

**Comment by ldelossa** [comment]
Interesting, I'm able to get a steam tray icon: 
![image](https://github.com/user-attachments/assets/62d86d5a-0954-4353-b22a-6169f3c41666)

But this is via install from `dnf` on Fedora :thinking: 
Could be something odd about flatpak stuff...

**Comment by sand-r** [comment]
Yes it's probably related to flatpak permissions. I had to add  socket=session-bus (D-bus session bus)  permission to steam to get the tray icon working with waybar, if that permission isn't set, it doesn't even work there.

**Comment by ldelossa** [comment]
Software bug! Just pushed the fix. 

![image](https://github.com/user-attachments/assets/f56d2ceb-0b98-4711-a33a-0d99564f3887)

**Comment by sand-r** [comment]
can confirm, works here now too. The only icon I still see issues with is the above mentioned flatpak steam.
![image](https://github.com/user-attachments/assets/f8a460c6-ffca-4309-9468-ebbfe6702c85)

**Comment by ldelossa** [comment]
Cool, unfortunately flatpack steam wont start for me. For some reason, it complains about my config directory and how it cant symlink it. Something with bwrap. 

Instead, can you: 
1. Close flatpak steam
2. Kill way-shell
3. Start way-shell and pipe all logs into a text file
4. Start flatpak steam. 

Then, upload the text file to me, either as an attachment or a gist.

**Comment by sand-r** [comment]
[https://gist.github.com/sand-r/13add5cb073cdfe035c86b44535434e9](url)

**Comment by sand-r** [comment]
[way-shell.log](https://github.com/user-attachments/files/17198323/way-shell.log)

**Comment by ldelossa** [comment]
Thanks. I see the issue:

```
dict entry(
         string "IconName"
         variant             string "steam_tray_mono"
      )
      dict entry(
         string "IconThemePath"
         variant             string "/home/louis/.var/app/com.valvesoftware.Steam/.local/share/Steam/public"
      )
```

My implementation is not loading icons from any `IconThemePath`. I'll figure this out soon.

**Comment by ldelossa** [comment]
Okay @sand-r should be fixed: 
![image](https://github.com/user-attachments/assets/675e3a25-f20b-4cbb-ae4f-92fc114ae94d)

This is running flatpak steam.

**Comment by sand-r** [comment]
Fixed, thanks!

**Comment by ldelossa** [comment]
Great. Fixed one other glaring issue this morning. Just cut release with this feature. I'll leave the issue open for any bugs that come in

**Comment by ldelossa** [comment]
Going to close this and mark it as complete. Been daily driving it without any bugs for a bit now :)
