### ISSUE TITLE
Bar is very tall all of a sudden

### ISSUE THREAD

**Issue by rosefromthedead** [ldelossa/way-shell#60]
![](https://media.tech.lgbt/media_attachments/files/113/170/713/629/056/056/original/10620287568afee4.png)

I have no idea what caused this or where to start looking for a fix, hopefully someone knows :P

**Comment by ldelossa** [comment]
I've seen this happen when gtk4-layer-shell becomes unavailable. Did you happen to remove, or do something to your system, which may have removed this shared library?

**Comment by rosefromthedead** [comment]
No:
```
$ ldd way-shell | grep layer
	libgtk4-layer-shell.so.0 => /usr/lib/libgtk4-layer-shell.so.0 (0x00007fc14e1fe000)
```

I ran gtk4-layer-demo and it looks normal..

**Comment by ldelossa** [comment]
Odd, can you dump the logs from stdout into a text file and share?

**Comment by rosefromthedead** [comment]
[way-shell.log](https://github.com/user-attachments/files/17084071/way-shell.log)
here's me opening it from main and ^C'ing shortly after

I should say, this doesn't seem to be because of a change in way-shell; old and new versions are all misbehaving in the same way

**Comment by rosefromthedead** [comment]
There was a gtk4-layer-shell update in Arch recently, but downgrading to the previous version didn't fix it. Neither did downgrading gtk4 :(

**Comment by ldelossa** [comment]
Are you building locally or using a package manager?

**Comment by rosefromthedead** [comment]
Building locally with `make && ./way-shell`

**Comment by ldelossa** [comment]
Try a "make clean && git clean -xdf" and build again, maybe something some old objects are laying around

**Comment by rosefromthedead** [comment]
Nope, same stuff. I tried installing the latest schema xml in /usr/... and rebuilding the schema for good measure but no luck there either. FWIW I have an old copy of way-shell from the AUR installed in /usr/ and that has the same problem.

**Comment by rosefromthedead** [comment]
My friend, also on Arch, can reproduce. My Fedora machine does not have the problem, with way-shell installed from copr

**Comment by Foxinatel** [comment]
Seems to be an issue with libadwaita 1.6, which is causing the `height-request` property of the panel to be set to 200. Downgrading libadwaita to 1.5.4 returns behavior to normal.
